const courseList = `<option value="Agriculture">Agriculture</option>
<option value="Agricultural Economics">Agricultural Economics</option>
<option value="Agricultural Extension">Agricultural Extension</option>
<option value="Agronomy">Agronomy</option>
<option value="Animal Science">Animal Science</option>
<option value="Crop Science">Crop Science</option>
<option value="Food Science and Technology">Food Science and Technology</option>
<option value="Fisheries">Fisheries</option>
<option value="Forest Resources Management (Forestry)">Forest Resources Management (Forestry)</option>
<option value="Home Science, Nutrition and Dietetics">Home Science, Nutrition and Dietetics</option>
<option value="Soil Science">Soil Science</option>
<option value="Archeology and Tourism">Archeology and Tourism</option>
<option value="Arabic and Islamic Studies">Arabic and Islamic Studies</option>
<option value="Christian Religious Studies">Christian Religious Studies</option>
<option value="English and Literary Studies">English and Literary Studies</option>
<option value="Fine and Applied Arts (Creatiuve Arts)">Fine and Applied Arts (Creatiuve Arts)</option>
<option value="Foreign Languages and Literature">Foreign Languages and Literature</option>
<option value="History and International Studies">History and International Studies</option>
<option value="Linguistics and Nigerian Languages">Linguistics and Nigerian Languages</option>
<option value="Mass Communication (Communication and Language Arts)">Mass Communication (Communication and Language Arts)</option>
<option value="Music">Music</option>
<option value="Theatre and Film Studies">Theatre and Film Studies</option>
<option value="Biochemistry">Biochemistry</option>
<option value="Botany">Botany</option>
<option value="Microbiology">Microbiology</option>
<option value="Marine Biology">Marine Biology</option>
<option value="Cell Biology & Genetics">Cell Biology & Genetics</option>
<option value="Zoology">Zoology</option>
<option value="Accountancy">Accountancy</option>
<option value="Acturial Science">Acturial Science</option>
<option value="Business Administration">Business Administration</option>
<option value="Business Management">Business Management</option>
<option value="Banking and Finance">Banking and Finance</option>
<option value="Hospitality and Tourism">Hospitality and Tourism</option>
<option value="Marketing">Marketing</option>
<option value="Industrial Relations and Personnel Management">Industrial Relations and Personnel Management</option>
<option value="Child Dental Health">Child Dental Health</option>
<option value="Oral and Maxillofacial Surgery">Oral and Maxillofacial Surgery</option>
<option value="Preventive Dentistry">Preventive Dentistry</option>
<option value="Restorative Dentistry">Restorative Dentistry</option>
<option value="Adult Education and Extra-Mural Studies">Adult Education and Extra-Mural Studies</option>
<option value="Arts Education">Arts Education</option>
<option value="Education & Accountancy">Education & Accountancy</option>
<option value="Education & Computer Science">Education & Computer Science</option>
<option value="Education & Economics">Education & Economics</option>
<option value="Education & Mathematics">Education & Mathematics</option>
<option value="Education & Physics">Education & Physics</option>
<option value="Education & Religious Studies">Education & Religious Studies</option>
<option value="Education & Social Science">Education & Social Science</option>
<option value="Education And Biology">Education And Biology</option>
<option value="Education And Chemistry">Education And Chemistry</option>
<option value="Education And English Language">Education And English Language</option>
<option value="Education And French">Education And French</option>
<option value="Education And Geography/Physics">Education And Geography/Physics</option>
<option value="Education And Political Science">Education And Political Science</option>
<option value="Educational Foundations">Educational Foundations</option>
<option value="Educational / Psychology Guidance And Counselling">Educational / Psychology Guidance And Counselling</option>
<option value="Health and Physical Education">Health and Physical Education</option>
<option value="Library and Information Science">Library and Information Science</option>
<option value="Science Education">Science Education</option>
<option value="Social Sciences Education">Social Sciences Education</option>
<option value="Vocational Teacher Education (Technical Education)">Vocational Teacher Education (Technical Education)</option>
<option value="Religion">Religion</option>
<option value="Igbo Linguistics">Igbo Linguistics</option>
<option value="Agricultural and Bioresources Engineering">Agricultural and Bioresources Engineering</option>
<option value="Civil Engineering">Civil Engineering</option>
<option value="Chemical Engineering">Chemical Engineering</option>
<option value="Computer Engineering">Computer Engineering</option>
<option value="Electrical Engineering">Electrical Engineering</option>
<option value="Electronic Engineering">Electronic Engineering</option>
<option value="Marine Engineering">Marine Engineering</option>
<option value="Mechanical Engineering">Mechanical Engineering</option>
<option value="Metallurgical and Materials Engineering">Metallurgical and Materials Engineering</option>
<option value="Petroleum and Gas Engineering">Petroleum and Gas Engineering</option>
<option value="Systems Engineering">Systems Engineering</option>
<option value="Structural Engineering">Structural Engineering</option>
<option value="Production and Industrial Engineering">Production and Industrial Engineering</option>
<option value="Architecture">Architecture</option>
<option value="Estate Management">Estate Management</option>
<option value="Quantity Surveying">Quantity Surveying</option>
<option value="Building">Building</option>
<option value="Geoinformatics and Surveying">Geoinformatics and Surveying</option>
<option value="Urban and Regional Planning">Urban and Regional Planning</option>
<option value="Health Administration and Management">Health Administration and Management</option>
<option value="Medical Laboratory Sciences">Medical Laboratory Sciences</option>
<option value="Medical Radiography and Radiological Sciences">Medical Radiography and Radiological Sciences</option>
<option value="Medical Rehabilitation">Medical Rehabilitation</option>
<option value="Nursing Sciences">Nursing Sciences</option>
<option value="Commercial and Property Law">Commercial and Property Law</option>
<option value="International and Jurisprudence">International and Jurisprudence</option>
<option value="Private and Public Law">Private and Public Law</option>
<option value="Anatomy">Anatomy</option>
<option value="Anesthesia">Anesthesia</option>
<option value="Chemical Pathology">Chemical Pathology</option>
<option value="Community Medicine">Community Medicine</option>
<option value="Dermatology">Dermatology</option>
<option value="Hematology and Immunology">Hematology and Immunology</option>
<option value="Medical Biochemistry">Medical Biochemistry</option>
<option value="Medical Microbiology">Medical Microbiology</option>
<option value="Medicine">Medicine</option>
<option value="Morbid Anatomy">Morbid Anatomy</option>
<option value="Obstetrics and Gynecology">Obstetrics and Gynecology</option>
<option value="Ophthalmology">Ophthalmology</option>
<option value="Otolaryngology">Otolaryngology</option>
<option value="Pediatrics">Pediatrics</option>
<option value="Pharmacology and Therapeutics">Pharmacology and Therapeutics</option>
<option value="Physiology">Physiology</option>
<option value="Radiation Medicine">Radiation Medicine</option>
<option value="Surgery">Surgery</option>
<option value="Psychological Medicine">Psychological Medicine</option>
<option value="Child Dental Health">Child Dental Health</option>
<option value="Clinical Pharmacy and Pharmacy Management">Clinical Pharmacy and Pharmacy Management</option>
<option value="Pharmaceutical Chemistry and Industrial Pharmacy">Pharmaceutical Chemistry and Industrial Pharmacy</option>
<option value="Pharmaceutical Technology and Industrial Pharmacy">Pharmaceutical Technology and Industrial Pharmacy</option>
<option value="Pharmaceutics">Pharmaceutics</option>
<option value="Pharmacognosy">Pharmacognosy</option>
<option value="Department of Pharmacology and Toxicology">Department of Pharmacology and Toxicology</option>
<option value="Computer Science">Computer Science</option>
<option value="Geology">Geology</option>
<option value="Mathematics">Mathematics</option>
<option value="Physics and Astronomy">Physics and Astronomy</option>
<option value="Geophysics">Geophysics</option>
<option value="Pure and Industrial Chemistry">Pure and Industrial Chemistry</option>
<option value="Statistics">Statistics</option>
<option value="Economics">Economics</option>
<option value="Geography">Geography</option>
<option value="Philosophy">Philosophy</option>
<option value="Political Science">Political Science</option>
<option value="Psychology">Psychology</option>
<option value="Public Administration and Local Government">Public Administration and Local Government</option>
<option value="Religion">Religion</option>
<option value="Social Work">Social Work</option>
<option value="Sociology/Anthropology">Sociology/Anthropology</option>
<option value="Veterinary Physiology/Pharmacology">Veterinary Physiology/Pharmacology</option>
<option value="Veterinary Anatomy">Veterinary Anatomy</option>
<option value="Animal Health and Production">Animal Health and Production</option>
<option value="Veterinary Parasitology and Entomology">Veterinary Parasitology and Entomology</option>
<option value="Veterinary Pathology and Microbiology">Veterinary Pathology and Microbiology</option>
<option value="Veterinary Public Health and Preventive Medicine">Veterinary Public Health and Preventive Medicine</option>
<option value="Veterinary Surgery">Veterinary Surgery</option>
<option value="Veterinary Medicine">Veterinary Medicine</option>
<option value="Veterinary Obstetrics and Reproductive Diseases">Veterinary Obstetrics and Reproductive Diseases</option>
<option value="Veterinary Teaching Hospital">Veterinary Teaching Hospital</option>`;

const addressList = `<option value="Afganistan">Afghanistan</option>
<option value="Albania">Albania</option>
<option value="Algeria">Algeria</option>
<option value="American Samoa">American Samoa</option>
<option value="Andorra">Andorra</option>
<option value="Angola">Angola</option>
<option value="Anguilla">Anguilla</option>
<option value="Antigua & Barbuda">Antigua & Barbuda</option>
<option value="Argentina">Argentina</option>
<option value="Armenia">Armenia</option>
<option value="Aruba">Aruba</option>
<option value="Australia">Australia</option>
<option value="Austria">Austria</option>
<option value="Azerbaijan">Azerbaijan</option>
<option value="Bahamas">Bahamas</option>
<option value="Bahrain">Bahrain</option>
<option value="Bangladesh">Bangladesh</option>
<option value="Barbados">Barbados</option>
<option value="Belarus">Belarus</option>
<option value="Belgium">Belgium</option>
<option value="Belize">Belize</option>
<option value="Benin">Benin</option>
<option value="Bermuda">Bermuda</option>
<option value="Bhutan">Bhutan</option>
<option value="Bolivia">Bolivia</option>
<option value="Bonaire">Bonaire</option>
<option value="Bosnia & Herzegovina">
    Bosnia & Herzegovina
</option>
<option value="Botswana">Botswana</option>
<option value="Brazil">Brazil</option>
<option value="British Indian Ocean Ter">
    British Indian Ocean Ter
</option>
<option value="Brunei">Brunei</option>
<option value="Bulgaria">Bulgaria</option>
<option value="Burkina Faso">Burkina Faso</option>
<option value="Burundi">Burundi</option>
<option value="Cambodia">Cambodia</option>
<option value="Cameroon">Cameroon</option>
<option value="Canada">Canada</option>
<option value="Canary Islands">Canary Islands</option>
<option value="Cape Verde">Cape Verde</option>
<option value="Cayman Islands">Cayman Islands</option>
<option value="Central African Republic">
    Central African Republic
</option>
<option value="Chad">Chad</option>
<option value="Channel Islands">Channel Islands</option>
<option value="Chile">Chile</option>
<option value="China">China</option>
<option value="Christmas Island">Christmas Island</option>
<option value="Cocos Island">Cocos Island</option>
<option value="Colombia">Colombia</option>
<option value="Comoros">Comoros</option>
<option value="Congo">Congo</option>
<option value="Cook Islands">Cook Islands</option>
<option value="Costa Rica">Costa Rica</option>
<option value="Cote DIvoire">Cote DIvoire</option>
<option value="Croatia">Croatia</option>
<option value="Cuba">Cuba</option>
<option value="Curaco">Curacao</option>
<option value="Cyprus">Cyprus</option>
<option value="Czech Republic">Czech Republic</option>
<option value="Denmark">Denmark</option>
<option value="Djibouti">Djibouti</option>
<option value="Dominica">Dominica</option>
<option value="Dominican Republic">Dominican Republic</option>
<option value="East Timor">East Timor</option>
<option value="Ecuador">Ecuador</option>
<option value="Egypt">Egypt</option>
<option value="El Salvador">El Salvador</option>
<option value="Equatorial Guinea">Equatorial Guinea</option>
<option value="Eritrea">Eritrea</option>
<option value="Estonia">Estonia</option>
<option value="Ethiopia">Ethiopia</option>
<option value="Falkland Islands">Falkland Islands</option>
<option value="Faroe Islands">Faroe Islands</option>
<option value="Fiji">Fiji</option>
<option value="Finland">Finland</option>
<option value="France">France</option>
<option value="French Guiana">French Guiana</option>
<option value="French Polynesia">French Polynesia</option>
<option value="French Southern Ter">
    French Southern Ter
</option>
<option value="Gabon">Gabon</option>
<option value="Gambia">Gambia</option>
<option value="Georgia">Georgia</option>
<option value="Germany">Germany</option>
<option value="Ghana">Ghana</option>
<option value="Gibraltar">Gibraltar</option>
<option value="Great Britain">Great Britain</option>
<option value="Greece">Greece</option>
<option value="Greenland">Greenland</option>
<option value="Grenada">Grenada</option>
<option value="Guadeloupe">Guadeloupe</option>
<option value="Guam">Guam</option>
<option value="Guatemala">Guatemala</option>
<option value="Guinea">Guinea</option>
<option value="Guyana">Guyana</option>
<option value="Haiti">Haiti</option>
<option value="Hawaii">Hawaii</option>
<option value="Honduras">Honduras</option>
<option value="Hong Kong">Hong Kong</option>
<option value="Hungary">Hungary</option>
<option value="Iceland">Iceland</option>
<option value="Indonesia">Indonesia</option>
<option value="India">India</option>
<option value="Iran">Iran</option>
<option value="Iraq">Iraq</option>
<option value="Ireland">Ireland</option>
<option value="Isle of Man">Isle of Man</option>
<option value="Israel">Israel</option>
<option value="Italy">Italy</option>
<option value="Jamaica">Jamaica</option>
<option value="Japan">Japan</option>
<option value="Jordan">Jordan</option>
<option value="Kazakhstan">Kazakhstan</option>
<option value="Kenya">Kenya</option>
<option value="Kiribati">Kiribati</option>
<option value="Korea North">Korea North</option>
<option value="Korea Sout">Korea South</option>
<option value="Kuwait">Kuwait</option>
<option value="Kyrgyzstan">Kyrgyzstan</option>
<option value="Laos">Laos</option>
<option value="Latvia">Latvia</option>
<option value="Lebanon">Lebanon</option>
<option value="Lesotho">Lesotho</option>
<option value="Liberia">Liberia</option>
<option value="Libya">Libya</option>
<option value="Liechtenstein">Liechtenstein</option>
<option value="Lithuania">Lithuania</option>
<option value="Luxembourg">Luxembourg</option>
<option value="Macau">Macau</option>
<option value="Macedonia">Macedonia</option>
<option value="Madagascar">Madagascar</option>
<option value="Malaysia">Malaysia</option>
<option value="Malawi">Malawi</option>
<option value="Maldives">Maldives</option>
<option value="Mali">Mali</option>
<option value="Malta">Malta</option>
<option value="Marshall Islands">Marshall Islands</option>
<option value="Martinique">Martinique</option>
<option value="Mauritania">Mauritania</option>
<option value="Mauritius">Mauritius</option>
<option value="Mayotte">Mayotte</option>
<option value="Mexico">Mexico</option>
<option value="Midway Islands">Midway Islands</option>
<option value="Moldova">Moldova</option>
<option value="Monaco">Monaco</option>
<option value="Mongolia">Mongolia</option>
<option value="Montserrat">Montserrat</option>
<option value="Morocco">Morocco</option>
<option value="Mozambique">Mozambique</option>
<option value="Myanmar">Myanmar</option>
<option value="Nambia">Nambia</option>
<option value="Nauru">Nauru</option>
<option value="Nepal">Nepal</option>
<option value="Netherland Antilles">
    Netherland Antilles
</option>
<option value="Netherlands">
    Netherlands (Holland, Europe)
</option>
<option value="Nevis">Nevis</option>
<option value="New Caledonia">New Caledonia</option>
<option value="New Zealand">New Zealand</option>
<option value="Nicaragua">Nicaragua</option>
<option value="Niger">Niger</option>
<option value="Nigeria">Nigeria</option>
<option value="Niue">Niue</option>
<option value="Norfolk Island">Norfolk Island</option>
<option value="Norway">Norway</option>
<option value="Oman">Oman</option>
<option value="Pakistan">Pakistan</option>
<option value="Palau Island">Palau Island</option>
<option value="Palestine">Palestine</option>
<option value="Panama">Panama</option>
<option value="Papua New Guinea">Papua New Guinea</option>
<option value="Paraguay">Paraguay</option>
<option value="Peru">Peru</option>
<option value="Phillipines">Philippines</option>
<option value="Pitcairn Island">Pitcairn Island</option>
<option value="Poland">Poland</option>
<option value="Portugal">Portugal</option>
<option value="Puerto Rico">Puerto Rico</option>
<option value="Qatar">Qatar</option>
<option value="Republic of Montenegro">
    Republic of Montenegro
</option>
<option value="Republic of Serbia">Republic of Serbia</option>
<option value="Reunion">Reunion</option>
<option value="Romania">Romania</option>
<option value="Russia">Russia</option>
<option value="Rwanda">Rwanda</option>
<option value="St Barthelemy">St Barthelemy</option>
<option value="St Eustatius">St Eustatius</option>
<option value="St Helena">St Helena</option>
<option value="St Kitts-Nevis">St Kitts-Nevis</option>
<option value="St Lucia">St Lucia</option>
<option value="St Maarten">St Maarten</option>
<option value="St Pierre & Miquelon">
    St Pierre & Miquelon
</option>
<option value="St Vincent & Grenadines">
    St Vincent & Grenadines
</option>
<option value="Saipan">Saipan</option>
<option value="Samoa">Samoa</option>
<option value="Samoa American">Samoa American</option>
<option value="San Marino">San Marino</option>
<option value="Sao Tome & Principe">
    Sao Tome & Principe
</option>
<option value="Saudi Arabia">Saudi Arabia</option>
<option value="Senegal">Senegal</option>
<option value="Seychelles">Seychelles</option>
<option value="Sierra Leone">Sierra Leone</option>
<option value="Singapore">Singapore</option>
<option value="Slovakia">Slovakia</option>
<option value="Slovenia">Slovenia</option>
<option value="Solomon Islands">Solomon Islands</option>
<option value="Somalia">Somalia</option>
<option value="South Africa">South Africa</option>
<option value="Spain">Spain</option>
<option value="Sri Lanka">Sri Lanka</option>
<option value="Sudan">Sudan</option>
<option value="Suriname">Suriname</option>
<option value="Swaziland">Swaziland</option>
<option value="Sweden">Sweden</option>
<option value="Switzerland">Switzerland</option>
<option value="Syria">Syria</option>
<option value="Tahiti">Tahiti</option>
<option value="Taiwan">Taiwan</option>
<option value="Tajikistan">Tajikistan</option>
<option value="Tanzania">Tanzania</option>
<option value="Thailand">Thailand</option>
<option value="Togo">Togo</option>
<option value="Tokelau">Tokelau</option>
<option value="Tonga">Tonga</option>
<option value="Trinidad & Tobago">Trinidad & Tobago</option>
<option value="Tunisia">Tunisia</option>
<option value="Turkey">Turkey</option>
<option value="Turkmenistan">Turkmenistan</option>
<option value="Turks & Caicos Is">Turks & Caicos Is</option>
<option value="Tuvalu">Tuvalu</option>
<option value="Uganda">Uganda</option>
<option value="United Kingdom">United Kingdom</option>
<option value="Ukraine">Ukraine</option>
<option value="United Arab Erimates">
    United Arab Emirates
</option>
<option value="United States of America">
    United States of America
</option>
<option value="Uraguay">Uruguay</option>
<option value="Uzbekistan">Uzbekistan</option>
<option value="Vanuatu">Vanuatu</option>
<option value="Vatican City State">Vatican City State</option>
<option value="Venezuela">Venezuela</option>
<option value="Vietnam">Vietnam</option>
<option value="Virgin Islands (Brit)">
    Virgin Islands (Brit)
</option>
<option value="Virgin Islands (USA)">
    Virgin Islands (USA)
</option>
<option value="Wake Island">Wake Island</option>
<option value="Wallis & Futana Is">Wallis & Futana Is</option>
<option value="Yemen">Yemen</option>
<option value="Zaire">Zaire</option>
<option value="Zambia">Zambia</option>
<option value="Zimbabwe">Zimbabwe</option>`;
